name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
        - absl-py==1.2.0
        - ansiwrap==0.8.4
        - anyio==3.6.1
        - argon2-cffi==21.3.0
        - argon2-cffi-bindings==21.2.0
        - astor==0.8.1
        - astroid==2.11.7
        - asttokens==2.0.8
        - astunparse==1.6.3
        - attrs==22.1.0
        - backcall==0.2.0
        - beautifulsoup4==4.8.0
        - besos==2.1.3
        - besos-examples==0.0.4
        - black==22.6.0
        - bleach==5.0.1
        - bokeh==2.4.3
        - cachetools==5.2.0
        - certifi==2022.6.15
        - cffi==1.15.1
        - charset-normalizer==2.1.1
        - chart-studio==1.1.0
        - click==8.1.3
        - cloudpickle==1.6.0
        - contexttimer==0.3.3
        - cycler==0.11.0
        - dask==2022.8.1
        - debugpy==1.6.3
        - decorator==5.1.1
        - defusedxml==0.7.1
        - Deprecated==1.2.13
        - dill==0.3.5.1
        - distributed==2022.8.1
        - entrypoints==0.4
        - eppy==0.5.59
        - et-xmlfile==1.1.0
        - executing==0.10.0
        - fastjsonschema==2.16.1
        - filterpy==1.4.5
        - flatbuffers==1.12
        - fonttools==4.35.0
        - fsspec==2022.7.1
        - future==0.18.2
        - gast==0.4.0
        - geomeppy==0.11.8
        - google-auth==2.11.0
        - google-auth-oauthlib==0.4.6
        - google-pasta==0.2.0
        - grpcio==1.47.0
        - h5py==3.7.0
        - HeapDict==1.0.1
        - idna==3.3
        - importlib-metadata==4.12.0
        - importlib-resources==5.9.0
        - influxdb==5.3.1
        - inspyred==1.0.1
        - ipykernel==6.15.1
        - ipysheet==0.5.0
        - ipython==8.4.0
        - ipython-genutils==0.2.0
        - ipywidgets==7.7.1
        - isort==5.10.1
        - jedi==0.18.1
        - Jinja2==3.1.2
        - joblib==1.1.0
        - jsonschema==4.10.0
        - jupyter==1.0.0
        - jupyter-client==7.3.4
        - jupyter-console==6.4.4
        - jupyter-core==4.11.1
        - jupyter-server==1.18.1
        - jupyterlab-pygments==0.2.2
        - jupyterlab-widgets==1.1.1
        - kiwisolver==1.4.4
        - lark-parser==0.12.0
        - lazy-object-proxy==1.7.1
        - libclang==14.0.6
        - locket==1.0.0
        - lxml==4.9.1
        - Markdown==3.4.1
        - MarkupSafe==2.1.1
        - matplotlib==3.2.2
        - matplotlib-inline==0.1.3
        - mccabe==0.7.0
        - mistune==0.8.4
        - msgpack==1.0.4
        - multiprocess==0.70.13
        - munch==2.5.0
        - mypy==0.971
        - mypy-extensions==0.4.3
        - nbclient==0.6.6
        - nbconvert==6.5.3
        - nbformat==5.4.0
        - nest-asyncio==1.5.5
        - notebook==6.4.12
        - numpy==1.23.2
        - oauthlib==3.2.0
        - openpyxl==3.0.10
        - opt-einsum==3.3.0
        - packaging==21.3
        - paho-mqtt==1.6.1
        - pandas==1.4.3
        - pandocfilters==1.5.0
        - papermill==2.4.0
        - parso==0.8.3
        - partd==1.3.0
        - pathos==0.2.9
        - pathspec==0.9.0
        - patsy==0.5.2
        - pexpect==4.8.0
        - pickleshare==0.7.5
        - pkgutil-resolve-name==1.3.10
        - platformdirs==2.5.2
        - Platypus-Opt==1.0.4
        - plotly==5.10.0
        - ply==3.11
        - pox==0.3.1
        - ppft==1.7.6.5
        - prometheus-client==0.14.1
        - prompt-toolkit==3.0.30
        - protobuf==3.19.4
        - psutil==5.9.1
        - ptyprocess==0.7.0
        - PuLP==2.6.0
        - pure-eval==0.2.2
        - pvlib==0.9.2
        - pyasn1==0.4.8
        - pyasn1-modules==0.2.8
        - pyclipper==1.3.0.post3
        - pycparser==2.21
        - pyDOE2==1.3.0
        - pydot3k==1.0.17
        - pyDots==1.1.17017
        - pyehub==1.4.2
        - pyepw==0.1
        - pyglet==1.5.0
        - Pygments==2.13.0
        - pyKriging==0.2.0
        - pylint==2.14.5
        - Pyomo==6.4.2
        - pyparsing==3.0.9
        - pypoly2tri==0.0.3
        - pyrsistent==0.18.1
        - python-dateutil==2.8.2
        - pytz==2022.2.1
        - PyYAML==6.0
        - pyzmq==23.2.1
        - qtconsole==5.3.1
        - QtPy==2.2.0
        - rbfopt==4.2.4
        - requests==2.28.1
        - requests-oauthlib==1.3.1
        - retrying==1.3.3
        - rsa==4.9
        - SALib==1.4.5
        - scikit-learn==1.1.2
        - scipy==1.9.0
        - seaborn==0.11.2
        - Send2Trash==1.8.0
        - Shapely==1.8.4
        - six==1.16.0
        - sklearn==0.0
        - sniffio==1.2.0
        - sortedcontainers==2.4.0
        - soupsieve==2.3.2.post1
        - stack-data==0.4.0
        - statsmodels==0.13.2
        - tblib==1.7.0
        - tenacity==8.0.1
        - tensorflow==2.7.0
        - termcolor==1.1.0
        - terminado==0.15.0
        - textwrap3==0.9.2
        - threadpoolctl==3.1.0
        - tinycss2==1.1.1
        - tinynumpy==1.2.1
        - tomli==2.0.1
        - tomlkit==0.11.4
        - toolz==0.12.0
        - torch==1.12.1
        - tornado==6.1
        - tqdm==4.64.0
        - traitlets==5.3.0
        - transforms3d==0.3.1
        - typing-extensions==4.3.0
        - urllib3==1.26.12
        - wcwidth==0.2.5
        - webencodings==0.5.1
        - websocket-client==1.3.3
        - Werkzeug==2.2.2
        - widgetsnbextension==3.6.1
        - wrapt==1.14.1
        - xlrd==2.0.1
        - zict==2.2.0
        - zipp==3.8.1
        - setuptools
        - git+https://github.com/building-energy/epw.git@master